### ISSUE TITLE
Does not work on old hardware with Firefox

### ISSUE THREAD

**Issue by green-coder** [oakes/play-cljc-examples#1]
When I browse the URL https://oakes.github.io/play-cljc-examples/super-koalio/,
the page does not show anything except the toggle music button and there is an error in the console.

![image](https://user-images.githubusercontent.com/598193/54823227-26df5080-4ce2-11e9-9bea-12248b570740.png)

I am using Firefox on MacOSX.

**Comment by oakes** [comment]
Hello, sorry for the delay, github didn't notify me of this. Are you using an old version of firefox? It's my main browser and definitely works for me.

**Comment by green-coder** [comment]
I believe it is a recent version.

```
{
  "application": {
    "name": "Firefox",
    "osVersion": "Darwin 17.7.0",
    "version": "66.0.2",
    "buildID": "20190326175229",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0) Gecko/20100101 Firefox/66.0",
    ...
  },
  ...
}
```

Maybe my hardware is too old?
![image](https://user-images.githubusercontent.com/598193/55288971-7c0e1700-53f2-11e9-8ef2-112a76efb1d2.png)

**Comment by oakes** [comment]
Yeah that is possible. Right now play-cljc requires WebGL 2. Do you get the same problem in chrome?

**Comment by green-coder** [comment]
It works in Chrome. The character jumps way out of the screen (too high, maybe a problem with the time measurement?), the colors are strange, but it works.

**Comment by oakes** [comment]
I might be doing something wrong with the timing, yeah. But I'm using `delta-time` to determine the distance to move the koala...I figured that would make it independent of FPS. Maybe not.

**Comment by Ondra09** [comment]
About jumping issue, I observed it in demo and in my project as well. It looks like GC collection is causing some lags in browser. Is there a way how to control GC strategy/run cycles?

**Comment by oakes** [comment]
There are probably unnecessary allocations happening, in the game and/or the library itself. I haven't spent enough time tracking those down yet, but I bet there are plenty of places where it's happening.

**Comment by oakes** [comment]
In particular, I think one big issue is that the data inside the entities is stored in immutable vectors and converted to the necessary mutable array every tick of the game loop. I am sure this conversion is expensive and generates garbage so I'll probably have to figure out a way to do this smarter.
