### ISSUE TITLE
Browser production built for examples does not run

### ISSUE THREAD

**Issue by FabianMk** [oakes/play-cljc-examples#2]
`clj -A:dev` works on my macOS: 10.15.5. I used `clj -A:prod:play-cljc` to build both examples for the browser. 
The browser (Chrome or Firefox) shows a blank page and logs `Uncaught DOMException: The operation is insecure.` in the web console.
What am I missing?

**Comment by oakes** [comment]
Most browsers don't let you load javascript from a `file://` url, so you'll need to run a local web server. I usually do `python -m SimpleHTTPServer` and it will spin up a web server in whatever directory i run it in.

**Comment by FabianMk** [comment]
Thanks. Releasing works like a charm, compared to all other game libraries I tried. Excited to do more with your library.
